version: 2

jobs:
    train:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run: conda env create -f data/envi.yaml
        - run: source activate skmer
        - run: mkdir -p data/genomes/raw
        - run: mkdir -p data/grdi_genomes/raw
        - run: cp .circleci/test_data/*.fasta data/genomes/raw
        - run: mv .circleci/test_data/*.fasta data/grdi_genomes/raw
        - run: cp .circleci/test_data/test_labels.xlsx data/no_ecoli_GenotypicAMR_Master.xlsx
        - run: mv .circleci/test_data/test_labels.xlsx "data/ResolvedCIPARS_SRL (1).xlsx"
        - run: snakemake
        - run: python src/model.py -x public -y grdi -a AMP -f 100 -i

    predict:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run: conda env create -f data/envi.yaml
        - run: source activate skmer
        - run: mkdir predict/genomes/raw
        - run: mv .circleci/test_data/SRR2407633.fasta predict/genomes/raw
        - run: mv .circleci/test_data/test_labels.xlsx predict/mic_labels.xlsx
        - run: snakemake -s predict/mic_clean.smk
        - run: snakemake -s predict/predict.smk
        - run: head predict/results.csv
        
    annotate:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run: conda env create -f data/envi.yaml
        - run: source activate skmer
        - run: mkdir predict/genomes/clean
        - run: mv .circleci/test_data/SRR2407633.fasta predict/genomes/clean
        - run: snakemake -s annotation/annotate.smk


workflows:
  version: 2
  all:
    jobs:
      - train:
      - predict:
      - annotate:
