version: 2.1

jobs:
    conda:
      docker:
        - image: bioconda/bioconda-utils-build-env
      steps:
        - checkout
        - run: conda env create -f data/envi.yaml
        - run: source activate skmer
        - persist_to_workspace:
            root: amr_predictor
            paths:
              - echo-output

    train:
      docker:
        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run: echo "in job train"
        - attach_workspace:
            at: amr_predictor
        - run:
            conda list | wc -l


    predict:
      docker:
        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run: echo "in job predict"
        - attach_workspace:
            at: amr_predictor
        - run:
            conda list | wc -l


    annotate:
      docker:
        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run: echo "in job annotate"
        - attach_workspace:
            at: amr_predictor
        - run:
            conda list | wc -l

workflows:
  version: 2
  all:
    jobs:
      - conda
      - train:
          requires:
            - conda
      - predict:
          requires:
            - conda
      - annotate:
          requires:
            - conda
            - train
