version: 2

jobs:
    train:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            command: |
              conda env create -f data/envi.yaml
              source activate skmer
              mkdir -p data/genomes/raw
              mkdir -p data/grdi_genomes/raw
              cp .circleci/test_data/*.fasta data/genomes/raw
              mv .circleci/test_data/*.fasta data/grdi_genomes/raw
              mv .circleci/test_data/test_labels.xlsx data/no_ecoli_GenotypicAMR_Master.xlsx
              mv .circleci/test_data/test_labels_grdi.xlsx "data/ResolvedCIPARS_SRL (1).xlsx"
              snakemake
              python src/model.py -x public -y grdi -a AMP -f 100 -i

    predict:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            command: |
              conda env create -f data/envi.yaml
              source activate skmer
              mkdir predict/genomes/raw
              mv .circleci/test_data/SRR2407633.fasta predict/genomes/raw
              mv .circleci/test_data/test_labels.xlsx predict/mic_labels.xlsx
              snakemake -s predict/mic_clean.smk
              snakemake -s predict/predict.smk
              head predict/results.csv

    annotate:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            command: |
              conda env create -f data/envi.yaml
              source activate skmer
              mkdir -p data/genomes/clean
              mv .circleci/test_data/SRR2407633.fasta data/genomes/clean
              conda install -c bioconda prokka 
              snakemake -s annotation/annotate.smk


workflows:
  version: 2
  all:
    jobs:
      - train
      - predict
      - annotate
